version: '3.7'

services:
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:6.8.8
    environment:
      - ELASTICSEARCH_HOSTS=http://10.0.2.4:9200
    ports:
      - 5601:5601